version: '3.5'

services:
  postgres:
    container_name: stock-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: top-secret
      POSTGRES_DB: stock_db
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
      # - ./postgresql.conf:/postgresql.conf
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.11.3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres-db:
  pgadmin:
    driver: local
