# Generated by Django 4.1.3 on 2023-05-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Bezeichnung")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="item/image",
                        verbose_name="Artikelbild",
                    ),
                ),
                (
                    "unit",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Stück"), (2, "Meter"), (3, "Rolle")],
                        default=1,
                        verbose_name="Maßeinheit",
                    ),
                ),
                (
                    "stock",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Lagerbestand"
                    ),
                ),
                ("ean", models.CharField(max_length=13, verbose_name="EAN")),
                (
                    "position_number",
                    models.IntegerField(
                        default=0, verbose_name="Position bei Hauptlager"
                    ),
                ),
                (
                    "barcode",
                    models.ImageField(
                        blank=True,
                        default="item/barcode/barcode.svg",
                        null=True,
                        upload_to="item/barcode",
                        verbose_name="Strichcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artikel",
                "verbose_name_plural": "Artikeln",
                "ordering": ("name",),
            },
        ),
    ]
