# Generated by Django 4.1.3 on 2024-02-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_item_on_stock_stock_alter_item_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Kategorie")),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorien",
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={
                "ordering": ("name",),
                "verbose_name": "Lager",
                "verbose_name_plural": "Lager",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="manufacturer_number",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Hersteller Artikelnummer"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="warehouse.category",
            ),
            preserve_default=False,
        ),
    ]
