# Generated by Django 4.1.3 on 2024-02-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_category_alter_stock_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Menge"),
        ),
        migrations.AlterField(
            model_name="item",
            name="barcode",
            field=models.ImageField(
                blank=True,
                default="item/barcode/barcode.svg",
                null=True,
                upload_to="barcode",
                verbose_name="Strichcode",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="warehouse.category",
                verbose_name="Kategorie",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="image", verbose_name="Artikelbild"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="warehouse.stock",
                verbose_name="Lager",
            ),
        ),
    ]
