# Generated by Django 4.1.3 on 2024-02-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0004_item_quantity_alter_item_barcode_alter_item_category_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
    ]
