# Generated by Django 4.1.3 on 2024-03-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0005_remove_item_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default-product-image.jpg",
                null=True,
                upload_to="image",
                verbose_name="Artikelbild",
            ),
        ),
    ]
