# Generated by Django 4.1.3 on 2024-03-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_employee"),
        ("warehouse", "0006_alter_item_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="erstellt am"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(default=0, verbose_name="menge"),
                ),
                (
                    "note",
                    models.TextField(blank=True, max_length=256, verbose_name="Notiz"),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="account.employee",
                        verbose_name="Mitarbeiter",
                    ),
                ),
                (
                    "item",
                    models.ManyToManyField(to="warehouse.item", verbose_name="Artikel"),
                ),
            ],
            options={
                "verbose_name": "Auftrag",
                "verbose_name_plural": "Aufträge",
                "ordering": ("created_at",),
            },
        ),
    ]
