# Generated by Django 4.1.3 on 2024-03-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0008_remove_order_item_remove_order_quantity_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Artikel", "verbose_name_plural": "Artikeln"},
        ),
    ]
