# Generated by Django 4.1.3 on 2024-04-17 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_employee"),
        ("warehouse", "0009_alter_orderitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="account.employee",
                verbose_name="Mitarbeiter",
            ),
        ),
    ]
