# Generated by Django 4.1.3 on 2024-08-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0011_alter_order_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="barcode",
            field=models.ImageField(
                blank=True, null=True, upload_to="barcode", verbose_name="Strichcode"
            ),
        ),
    ]
