# Generated by Django 4.1.3 on 2024-09-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0014_item_min_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="department",
            field=models.CharField(
                blank=True, default="AC", max_length=64, verbose_name="Abteilung"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="favorite",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Rot"), (2, "Gelb"), (3, "Grün")],
                default=3,
                verbose_name="Maßeinheit",
            ),
        ),
    ]
