# Generated by Django 4.1.3 on 2024-09-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0016_alter_item_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="favorite",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Rot"), (2, "Gelb"), (3, "Grün")],
                default="",
                verbose_name="Favorit",
            ),
        ),
    ]
