# Generated by Django 4.1.3 on 2024-09-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_options_alter_employee_user"),
        ("warehouse", "0018_alter_item_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In Bearbeitung"),
                            ("approved", "Bestätigt"),
                            ("rejected", "Zurückgewiesen"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retoure",
                "verbose_name_plural": "Retoure",
            },
        ),
        migrations.CreateModel(
            name="ReturnRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(default=0, verbose_name="menge"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_request_items",
                        to="warehouse.item",
                        verbose_name="Artikel",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.returnrequest",
                        verbose_name="Retoure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rückgabe Artikel",
                "verbose_name_plural": "Rückgabe Artikeln",
            },
        ),
    ]
