# Generated by Django 4.1.3 on 2024-10-17 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warehouse", "0019_returnrequest_returnrequestitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnrequest",
            name="reason",
            field=models.TextField(verbose_name="Rückgabegrund"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
