# Generated by Django 4.1.3 on 2024-10-17 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("warehouse", "0020_alter_returnrequest_reason_alter_stock_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Lagerleitung",
            ),
        ),
    ]
